//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebsite.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOOKUPRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOOKUPRole()
        {
            this.SYSUserRoles = new HashSet<SYSUserRole>();
        }
    
        public int LOOKUPRoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public int RowCreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public int RowModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSUserRole> SYSUserRoles { get; set; }
    }
}


// USE [DemoDB]
// GO

// CREATE TABLE [dbo].[LOOKUPRole](
//     [LOOKUPRoleID] [int] IDENTITY(1,1) NOT NULL,
//     [RoleName] [varchar](100) DEFAULT '',
//     [RoleDescription] [varchar](500) DEFAULT '',
//     [RowCreatedSYSUserID] [int] NOT NULL,
//     [RowCreatedDateTime] [datetime]  DEFAULT GETDATE(),
//     [RowModifiedSYSUserID] [int] NOT NULL,
//     [RowModifiedDateTime] [datetime] DEFAULT GETDATE(),
// PRIMARY KEY (LOOKUPRoleID)
//     )
// GO


// INSERT INTO LOOKUPRole(RoleName, RoleDescription, RowCreatedSYSUserID, RowModifiedSYSUserID)
//        VALUES('Admin','Can Edit, Update, Delete',1,1)
// INSERT INTO LOOKUPRole(RoleName, RoleDescription, RowCreatedSYSUserID, RowModifiedSYSUserID)
//        VALUES('Member','Read only',1,1)