//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWebsite.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSUserProfile
    {
        public int SYSUserProfileID { get; set; }
        public int SYSUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int RowCreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public int RowModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
    
        public virtual SYSUser SYSUser { get; set; }
    }
}


// USE [DemoDB]
// GO


// CREATE TABLE [dbo].[SYSUserProfile](
//     [SYSUserProfileID] [int] IDENTITY(1,1) NOT NULL,
//     [SYSUserID] [int] NOT NULL,
//     [FirstName] [varchar](50) NOT NULL,
//     [LastName] [varchar](50) NOT NULL,
//     [Gender] [char](1) NOT NULL,
//     [RowCreatedSYSUserID] [int] NOT NULL,
//     [RowCreatedDateTime] [datetime] DEFAULT GETDATE(),
//     [RowModifiedSYSUserID] [int] NOT NULL,
//     [RowModifiedDateTime] [datetime] DEFAULT GETDATE(),
//     PRIMARY KEY (SYSUserProfileID)
//     )
// GO

// ALTER TABLE [dbo].[SYSUserProfile]  WITH CHECK ADD FOREIGN KEY([SYSUserID])
// REFERENCES [dbo].[SYSUser] ([SYSUserID])
// GO